---

- name: Check if AWS CLI is installed
  ansible.builtin.command: /usr/bin/which aws
  register: awscli_facts
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: Set AWS CLI installation path
  ansible.builtin.set_fact:
    awscli_path: "{{ awscli_facts.stdout_lines[0] }}"
  when: awscli_facts.rc==0 and awscli_facts.stdout_lines|length>0

- name: Get current AWS CLI version
  ansible.builtin.command:
    argv:
      - "{{ awscli_path }}"
      - "--version"
  register: awscli_facts1
  when: awscli_facts.rc==0 and awscli_facts.stdout_lines|length>0
  changed_when: false
  check_mode: false

- name: Set var with current AWS CLI version
  ansible.builtin.set_fact:
    awscli_version: "{{ awscli_facts1.stdout_lines[0].split(' ')[0].split('/')[1] }}"
  when: awscli_facts.rc==0 and awscli_facts1.stdout_lines|length>0
  changed_when: false

- name: Get latest AWS CLI version from GitHub API
  ansible.builtin.uri:
    url: https://api.github.com/repos/aws/aws-cli/tags
  register: awsgithub_facts
  ignore_errors: true
  check_mode: false

- name: Set var with latest AWS CLI version
  ansible.builtin.set_fact:
    awscli_lastversion: "{{ awsgithub_facts.json[0].name }}"
  when: awsgithub_facts is defined and awsgithub_facts.status==200
  changed_when: false

- name: Determine AWS CLI installation action required (install or update)
  ansible.builtin.set_fact:
    aws_installtype: "{%
                      if awscli_facts.rc==1 or (awscli_facts.rc==0 and awscli_version is defined and awscli_version.split('.')[0]|int<2) %}install{%
                      elif awscli_facts.rc==0 and awscli_version is defined and awscli_lastversion is defined and awscli_version!=awscli_lastversion %}update{%
                      else %}none{%
                      endif %}"
