---

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: awscli
  register: tempfolder
  changed_when: false

- name: Download awscli
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "{{ tempfolder.path }}"
    remote_src: true

- name: Installing awscli
  become: true
  ansible.builtin.command:
    cmd: "./install"
    chdir: "{{ tempfolder.path }}/aws/"
  when: aws_installtype=="install"

- name: Updating awscli
  become: true
  ansible.builtin.command:
    argv:
      - "./install"
      - "--update"
    chdir: "{{ tempfolder.path }}/aws/"
  when: aws_installtype=="update"

- name: Delete temporary directory
  ansible.builtin.file:
    path: "{{ tempfolder.path }}"
    state: absent
  no_log: true
  changed_when: false
