---

- ansible.builtin.getent:
    database: passwd
    key: "{{ item }}"
    split: ":"
  register: datauser
  with_items:
    - "{{ _user }}"

- name: set_fact default path user
  ansible.builtin.set_fact:
    _homepath: "{{ datauser.results[0].ansible_facts.getent_passwd[_user][4] }}"

- name: Create AWS configuration directory
  become: true
  ansible.builtin.file:
    path: "{{ _homepath }}/.aws"
    state: directory
    owner: "{{ _user }}"
    group: "{{ _user }}"
    mode: 0700
  with_items:
    - "{{ _user }}"

- name: Write AWS credentials file
  become: true
  ansible.builtin.template:
    src: credentials.j2
    dest: "{{ _homepath }}/.aws/credentials"
    owner: "{{ _user }}"
    group: "{{ _user }}"
    mode: 0600
  with_items:
    - "{{ _user }}"

- name: Write AWS config file
  become: true
  ansible.builtin.template:
    src: config.j2
    dest: "{{ _homepath }}/.aws/config"
    owner: "{{ _user }}"
    group: "{{ _user }}"
    mode: 0600
  with_items:
    - "{{ _user }}"
