---

- import_tasks: awscli_facts.yml

- name: Deleting awscli python package version prior 2
  become: true
  ansible.builtin.pip:
    name: awscli
    state: absent
  when: awscli_facts.rc==0 and awscli_version is defined and awscli_version.split('.')[0]|int<2

- import_tasks: awscli_v2.yml
  when: aws_installtype=="install" or aws_installtype=="update"

- include_tasks: awscli_configure.yml
  with_items: "{{ awscli_users }}"
  loop_control:
    loop_var: _user
  when: awscli_users is defined and awscli_users|length>0
